server:
  port: 8086

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      source: deactivatePatientByMPI
      bindings:
        deactivatePatientByMPI-out-0:
          destination: Patient-deactivation-event
    gcp:
      spanner:
        database: ${DB}
        instance-id: ${INSTANCE_ID}
        project-id: ${PROJECT_ID}
